# NumPy Array
la estructura central de NumPY

In [5]:
import numpy as np



In [ ]:
lista =[1,2,3,4,5,6,7,8,9]

arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
type(matriz)


list

In [ ]:
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
matrix=np.array(matriz)

type(matrix)

numpy.ndarray

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0]


1

In [ ]:
arr[0]+arr[3]

5

In [ ]:
matrix[0] 

array([1, 2, 3])

In [ ]:
matrix[0,1]

2

In [ ]:
#slicing
arr[0:3]

array([1, 2, 3])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# lo quiero todo pero de tres en tres, los pasos en los que quiero traer los arreglos
arr[::3]

array([1, 4, 7])

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#filas columnas
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])

In [16]:
arr = np.array([13, 6, 3, 5, 10])

arr[arr>7]

SyntaxError: ignored