In [1]:
import numpy as np

escalar

In [8]:
scalar =np.array(42)
print(scalar)
#para validar en numpy que es scalar usando numero de dimensiones
print('numero de dimensiones ') 
scalar.ndim


42
numero de dimensiones 


0

Vector

In [10]:
vector =np.array([1,2,3])
print(vector)
vector.ndim
print('numero de dimensiones ') 
vector.ndim


[1 2 3]
numero de dimensiones 


1

# Matriz

In [16]:
matriz =np.array([[1,2,3],[4,5,6]])
print(matriz)

print('numero de dimensiones ') 
matriz.ndim

[[1 2 3]
 [4 5 6]]
numero de dimensiones 


2

In [17]:
tensor =np.array([[[1,2,3],[4,5,6]],[[6,7,8],[0,7,5]]])
print(tensor)

print('numero de dimensiones ') 
tensor.ndim

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [0 7 5]]]
numero de dimensiones 


3

# agregaar o eliminar dimensiones 
ndmin =10  significa que el numero de dimensiones desde que lo defino tiene que ser 10 

In [19]:
vector =np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim
print('numero de dimensiones ') 
vector.ndim

#agr

[[[[[[[[[[1 2 3]]]]]]]]]]
numero de dimensiones 


10

# ahora si tengo un array y quiero expandierle una unica dimension en sus ejes

np.expand_dims

axis =0  significa que voy a expandir una dimension a nivel de filas

In [23]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
print('numero de dimensiones ') 
expand.ndim

[[1 2 3]]
numero de dimensiones 


2

# cuando quiero eliminar dimensiones que no estoy usando 

np.squeeze  comprime al numero correco de dimensiones que se esta usando , osea la que se cree correcta 

In [26]:
print(vector,vector.ndim)

vector_2=np.squeeze(vector)
print(vector_2,vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
