In [2]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
# valores de 0 a 10 con salto de 2 en 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
# define un array compuesto por ceros
np.zeros(3)

array([0., 0., 0.])

In [8]:
#tambien puedo crear esta tupla 
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
arr= np.ones((10,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
arr.astype(np.bool_)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
# de 0 a 10 y que  genere 10 datos
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [14]:
# crea una matriz con la diagonal principal en 1
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# valor aleatoria entre 0 y 1
np.random.rand()

0.5169743897943918

In [17]:
np.random.rand(4)

array([0.81695529, 0.14537421, 0.50540127, 0.88760918])

In [19]:
np.random.rand(4,4)

array([[0.5118734 , 0.38774986, 0.00464552, 0.90798054],
       [0.80551192, 0.12923924, 0.16974293, 0.89559157],
       [0.44790457, 0.33478407, 0.5222105 , 0.05270548],
       [0.71593354, 0.57762644, 0.71198675, 0.27532965]])

In [21]:
# random entero entre 1 y 15
np.random.randint(1,15)

3

In [22]:
# calores aleatorios de 0 a 100 pero en una tupla de 10 por 10
np.random.randint(1,100,(10,10))

array([[10, 20, 58, 59, 37, 48, 56, 70, 57, 47],
       [13, 81, 35, 45, 96, 78, 42, 39, 81, 96],
       [54, 20, 48, 43, 79, 46,  9, 21, 51, 77],
       [46, 56, 77, 46, 45, 68, 94, 44, 36, 53],
       [86, 65, 55, 52, 91, 23, 80, 10, 98, 23],
       [78, 25, 61,  2, 81, 72, 15, 64, 95, 13],
       [48, 84, 78, 28, 19, 47, 79, 57, 42, 36],
       [88, 77, 33,  1, 44, 97, 86, 43,  4, 67],
       [13, 39, 41, 24, 95, 19, 38, 78, 99, 62],
       [14, 69, 74, 55, 76, 93, 25, 23, 18,  6]])