In [1]:
import numpy as np

# shape dice la forma que tiene un arreglo



In [4]:
arr = np.random.randint(1,10,(3,2))
arr

array([[8, 3],
       [1, 9],
       [6, 9]])

In [5]:
arr.shape

(3, 2)

In [6]:
arr.reshape(1,6)

array([[8, 3, 1, 9, 6, 9]])

In [7]:
arr.reshape(2,3)

array([[8, 3, 1],
       [9, 6, 9]])

In [8]:
np.reshape(arr,(1,6))

array([[8, 3, 1, 9, 6, 9]])

#ahora vamos a ver como esta ordenando

In [9]:
arr

array([[8, 3],
       [1, 9],
       [6, 9]])

In [10]:
# reordenar como lo hace en el lenguaje C
np.reshape(arr,(2,3),'C')

array([[8, 3, 1],
       [9, 6, 9]])

In [12]:
# reordenar como lo hace en el lenguaje fortran
np.reshape(arr,(2,3),'F')

array([[8, 6, 9],
       [1, 3, 9]])

In [13]:
# reordenar como lo hace la optimizacion de mi sistema , de mi laptop
np.reshape(arr,(2,3),'A')

array([[8, 3, 1],
       [9, 6, 9]])