In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,20,10)
arr

array([ 2, 10,  9, 17,  3,  8,  1,  5, 14,  2])

In [5]:
matriz=arr.reshape(2,5)
matriz

array([[ 2, 10,  9, 17,  3],
       [ 8,  1,  5, 14,  2]])

# numero mas grande que tenga el array

In [7]:
arr.max()

17

In [8]:
matriz.max()

17

# que pasa si le digo que solo lo haga para el eje 1 osea fila

# 0 es por columna


In [10]:
matriz.max(1)

array([17, 14])

In [11]:
matriz.max(0)


array([ 8, 10,  9, 17,  3])

# indice donde se encuentra el valor mas grande

In [12]:
arr.argmax()

3

In [14]:
matriz.argmax(0) # aqui veo el indice del maximo por cada columna 

array([1, 0, 0, 0, 0])

# minimos


In [15]:
arr.min()

1

In [16]:
arr.argmin()

6

# de un pico a otro pico

de un pico mas bajo al mas alto cuantos datos hay

In [17]:
arr

array([ 2, 10,  9, 17,  3,  8,  1,  5, 14,  2])

In [18]:
arr.ptp()

16

In [19]:
matriz.ptp(0)

array([6, 9, 4, 3, 1])

# percentil me va a especificar directamente el percentil que estoy trabajando 

In [21]:
# percentil 50 o mediana
np.percentile(arr,50) # cual es el valor que se encuentra en la mitad

6.5

# sort me ordena de menor a mayor los numeros que tengo en el arreglo

In [23]:
arr.sort()
arr

array([ 1,  2,  2,  3,  5,  8,  9, 10, 14, 17])

# la mediana

In [24]:
np.median(arr)

6.5

In [25]:
np.median(matriz,1)

array([ 2., 10.])

Desviacion estandar

In [26]:
np.std(arr)

5.18555686498567

# varianza

In [27]:
np.var(arr)

26.890000000000004

# media


In [28]:
np.mean(arr)

7.1

# concatenar
unir array a con el b

In [42]:
a= np.array([[1,2],[3,4]])
b=np.array([5,6])


In [33]:
np.concatenate((a,b),axis=0) # da error porque b y a no tienen las mismas dimensiones

ValueError: ignored

In [34]:
a.ndim


2

In [43]:
b.ndim

1

# vamos a llevar a b a la misma dimension

In [44]:
b=np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [45]:
b.ndim

2

In [46]:
np.concatenate((a,b),axis=0) 

array([[1, 2],
       [3, 4],
       [5, 6]])

# para hacerlo columnar

In [48]:
b

array([[5, 6]])

In [47]:
# no funciona porque 5 y 6 no estan columnares se coluciona con reshape o transpueta
np.concatenate((a,b),axis=1)  

ValueError: ignored

In [49]:
# aqui usamos la transpuesta T
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [50]:
b.T

array([[5],
       [6]])