In [6]:
import numpy as np

a veces se puede hacer modificaciones que fallan y dañan el original entonces se usa copy para evitar perder 

In [8]:
arr =np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# vamos a hacer un slicing con las posiciones de la 0 a la 6

In [13]:
trozo_de_arr=arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

# vamos a convertir todos los valores del trozo a cero

In [14]:
trozo_de_arr[:]=0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

# ahora cuando veo** arr** noto que esta dañado , error fatal

In [15]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

# este problema lo puedo evitar  con copy

In [16]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [18]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [19]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

# siempre que queremos usar un trozo de un array debemos usar copy para no dañar el original 