In [1]:
import numpy as np

In [6]:
arr= np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [7]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
idx= arr > 5
idx

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [9]:
arr[idx]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [10]:
arr[(arr > 5) & (arr < 9 )]

array([6, 7, 8], dtype=int8)

# para la condicion cambiar por tal valor

In [12]:
arr[arr > 5]=99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [13]:
arr[arr==99]
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)