In [5]:
import numpy as np

In [6]:
lista=[1,2]
lista

[1, 2]

# aqui numpy en lugar de multiplicar los valores lo que hace es duplicarlos


In [8]:
lista * 2

[1, 2, 1, 2]

In [10]:
arr=np.arange(0,10)
arr2=arr.copy()

# operaciones aritmeticas

In [12]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2 *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
arr2 +2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
1/arr2 # si vemos hay error al dividir entre cero pero los demas datos estan

<ipython-input-20-4817e3bbb106>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr2 # si vemos hay error al dividir entre cero pero los demas datos estan


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [22]:
arr2 **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
arr2+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
matriz=arr.reshape(2,5)
matriz2=matriz.copy()

In [29]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
matriz +matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Producto punto


In [33]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [34]:
matriz @ matriz.T

array([[ 30,  80],
       [ 80, 255]])

2