In [1]:
import numpy as np

# identidad

In [4]:
identidad = np.eye(4)
# cuando le damos un valor a esta funcion nos devuelve una matriz
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
vector = np.array([[2],[3],[5],[7]])
vector

array([[2],
       [3],
       [5],
       [7]])

In [6]:
vector.shape

(4, 1)

In [7]:
identidad.dot(vector)

array([[2.],
       [3.],
       [5.],
       [7.]])

# inversa 

es la matriz que al operar matriz A por inversa da identidad


$A A^{-1} = Id$


In [9]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])

A


array([[ 1,  0,  1],
       [ 0,  1,  1],
       [-1,  1,  1]])

In [10]:
inversa_A=np.linalg.inv(A)
inversa_A

array([[ 0.,  1., -1.],
       [-1.,  2., -1.],
       [ 1., -1.,  1.]])

In [11]:
A.dot(inversa_A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

no siempre existe esta identidad y si no existe la llamamos matriz singular

In [13]:
singular = np.array([[1,1],[1,1]])
singular


array([[1, 1],
       [1, 1]])

In [14]:
np.linalg.inv(singular)

LinAlgError: ignored