https://wbd.ms/share/v2/aHR0cHM6Ly93aGl0ZWJvYXJkLm1pY3Jvc29mdC5jb20vYXBpL3YxLjAvd2hpdGVib2FyZHMvcmVkZWVtLzRlZmVmMGZjY2I4YzRiYTU4NGZmNWNjMjY1M2NhNGUxX0JCQTcxNzYyLTEyRTAtNDJFMS1CMzI0LTVCMTMxRjQyNEUzRF9jZmY4MGEyNS0xN2YwLTQ1YWYtODkxOC1jMTk2ZDdhODM0NzY=

In [1]:
import numpy as np

#pedirle a numpy que los resultados muy cercanos a 0
#me los muestre como 0

In [ ]:
np.set_printoptions(suppress=True)

In [2]:
A = np.array([[3,1],[2,1]])
A

array([[3, 1],
       [2, 1]])

In [3]:
b = np.array([[1],[1]])
b

array([[1],
       [1]])

In [4]:
inversa_A = np.linalg.inv(A)

inversa_A

array([[ 1., -1.],
       [-2.,  3.]])

In [6]:
x=inversa_A.dot(b)
x

array([[0.],
       [1.]])

In [7]:
A.dot(x)

array([[1.],
       [1.]])

solucion 2

In [8]:
sol_2 = inversa_A.dot(np.array([[3],[7]]))

sol_2

array([[-4.],
       [15.]])

In [9]:
A.dot(sol_2)

array([[3.],
       [7.]])