Una matriz es ortogonal cuando todas sus filas son mutuamente ortonormales y todas sus columnas son mutuamente ortonormales

In [2]:
import numpy as np

In [3]:
matriz = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]
                  ])
print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


para ver que es ortogonal esta matriz necesitamos comprobar que sus columnas son mutuamente ortonormales



In [5]:
# primera columna
matriz[:,0]

array([1, 0, 0])

In [7]:
# segunda columna
matriz[:,1]

array([0, 1, 0])



$$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$


$$
\begin{bmatrix}
v_1 & v_2 & v_3 \\
 &  &  \\
 &  & 
\end{bmatrix}
$$




para comprobar la ortogonalidad del vector 1(columna 1) respecto a v2

 $v_1 \perp v_2$

In [8]:

# la primer columna con el proudcto interno con la segunda columna
matriz[:,0].dot(matriz[:,1])

0

 $v_1 \perp v_3$

In [9]:
matriz[:,0].dot(matriz[:,2])

0

$v_2 \perp v_3$

In [10]:
matriz[:,1].dot(matriz[:,2])

0

para estar seguros que son ortonormales validamos su norma

In [11]:
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


In [12]:
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


ver la norma con respecto filas

In [13]:
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [14]:
A = np.array([[np.cos(100), -np.sin(100)],
             [np.sin(100), np.cos(100)]])
print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


queremos comprobar que esta matriz es ortogonal

In [15]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


empezamos a ver los problemas para representar computacionalmenbte , este numero deberia ser 1 pero es 0.999....

veamos que el angulo que forman entre ellos es cero

producto interno de una fila con la otra

y el producto interno de una columna con la otra

In [16]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


ahora queremos ver que 

In [17]:
A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

[[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]
[[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


In [18]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]
