In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [7]:
vector

array([3, 4, 5])

In [3]:
A = vector + matriz # no coinciden las dimensiones

ValueError: ignored

# brodcasting es extender la dimension de menor tamaño

In [4]:
C = matriz + 42
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [5]:
np.array([[42],[42],[42]])

array([[42],
       [42],
       [42]])

In [6]:
D = matriz + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]
