# pizarra online microsoft Whiteboard
https://wbd.ms/share/v2/aHR0cHM6Ly93aGl0ZWJvYXJkLm1pY3Jvc29mdC5jb20vYXBpL3YxLjAvd2hpdGVib2FyZHMvcmVkZWVtL2E5YWJhZTkxYjhhZjRmY2RhM2MxZTVlODBlMTU0N2E5X0JCQTcxNzYyLTEyRTAtNDJFMS1CMzI0LTVCMTMxRjQyNEUzRF9hMjJhMjlkMS1lYjI4LTRkNTUtYmIxZC1mMThlODc4MjE3MmM=

email jhonnatan.castano@

In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [5]:
vector

array([2, 3])

In [6]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
A = matriz * vector

In [4]:
A

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

In [7]:
B=matriz.dot(vector)

In [8]:
B

array([ 8, 18, 28])

In [9]:
B=matriz.dot(vector)
C=np.dot(matriz,vector)

In [10]:
C

array([ 8, 18, 28])