# pizarra

https://wbd.ms/share/v2/aHR0cHM6Ly93aGl0ZWJvYXJkLm1pY3Jvc29mdC5jb20vYXBpL3YxLjAvd2hpdGVib2FyZHMvcmVkZWVtLzc1YzczYzJjMmFlZjQ2NmE5YWZiOGNkZDdhYzU5YjBiX0JCQTcxNzYyLTEyRTAtNDJFMS1CMzI0LTVCMTMxRjQyNEUzRF8wOTI1ODk3OC0xYzMwLTRhMzAtYTFlMy1jOTFiNDY2ZThiNWM=



In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

# Asociativa

In [3]:

ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [4]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


#Distrbutiva

In [5]:

D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))

In [6]:
print(D)
print('')
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]

[[ 26  17]
 [ 62  41]
 [122  83]]


In [7]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


# conmutativa

In [8]:
F = B.dot(C)

In [9]:
G = C.dot(B)

In [10]:
print(F==G)

[[False False]
 [False False]]


In [11]:
F

array([[15,  7],
       [10,  4]])

In [12]:
G

array([[ 5, 10],
       [ 8, 14]])

# la multiplicacion de vectores si es conmutativa

In [18]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])
print(v1)

print('')
print(v2)

[[2]
 [7]]

[[3]
 [5]]


In [15]:
v1_tv2 = v1.T.dot(v2)
v1_tv2

array([[41]])

In [17]:
v2_tv1 = v2.T.dot(v1)
v2_tv1

array([[41]])