pizarra whiteboard

https://wbd.ms/share/v2/aHR0cHM6Ly93aGl0ZWJvYXJkLm1pY3Jvc29mdC5jb20vYXBpL3YxLjAvd2hpdGVib2FyZHMvcmVkZWVtL2UxYzljYmJjNWU1NjQ4OGY4ZDU2MDc4MDYwNzVjMzYzX0JCQTcxNzYyLTEyRTAtNDJFMS1CMzI0LTVCMTMxRjQyNEUzRF8zN2M2MmUxNS04NjE0LTRhNzMtODFhYy0wYjA0NDhjMzk0ZDQ=

In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])

In [3]:
A

array([[ 2,  3],
       [ 5,  7],
       [11, 13]])

In [4]:
B

array([[1, 3],
       [2, 1]])

In [6]:
AB_t=A.dot(B).T
AB_t

array([[ 8, 19, 37],
       [ 9, 22, 46]])

In [7]:
B_tA_t=B.T.dot(A.T)

In [8]:
print(AB_t ==B_tA_t )

[[ True  True  True]
 [ True  True  True]]
