In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [2]:
%cd '/content/drive/My Drive/Colab Notebooks/pandas/db'
!ls

/content/drive/My Drive/Colab Notebooks/pandas/db
Meteorite_Landings.csv	test.csv  test.json	test.pkl
poblacion.csv		test.hdf  test.parquet	test.xlsx


In [3]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.5'

In [4]:
pd.options.display.float_format='{:.2f}.'.format  # para que nos muestren las cosas con dos decimales

In [5]:
np.set_printoptions(precision=2) #hacemos lo mismo con numpay 2 decimales

In [6]:
np.random.rand() 

0.32634548443653555

In [8]:
np.random.randn() 

-0.22047712059735547

In [14]:
x1=np.random.rand(2,5)*10
x1

array([[7.46, 5.03, 5.07, 4.32, 3.95],
       [3.4 , 3.53, 0.3 , 0.33, 3.1 ]])

In [12]:
x2=np.random.rand(2,5)*-1
x2

array([[-0.53, -0.3 , -0.87, -0.79, -0.84],
       [-0.7 , -0.11, -0.66, -0.18, -0.63]])

In [15]:
np.concatenate([x1,x2])

array([[ 7.46,  5.03,  5.07,  4.32,  3.95],
       [ 3.4 ,  3.53,  0.3 ,  0.33,  3.1 ],
       [-0.53, -0.3 , -0.87, -0.79, -0.84],
       [-0.7 , -0.11, -0.66, -0.18, -0.63]])

In [16]:
np.concatenate([x1,x2]).shape

(4, 5)

In [17]:
np.concatenate([x1,x2],axis=1)

array([[ 7.46,  5.03,  5.07,  4.32,  3.95, -0.53, -0.3 , -0.87, -0.79,
        -0.84],
       [ 3.4 ,  3.53,  0.3 ,  0.33,  3.1 , -0.7 , -0.11, -0.66, -0.18,
        -0.63]])

In [18]:
np.concatenate([x1,x2],axis=1).shape

(2, 10)

In [24]:
s1=pd.Series(x1[0],index=['a','b','c','d','e'])
s1

a   7.46.
b   5.03.
c   5.07.
d   4.32.
e   3.95.
dtype: float64

In [25]:
s2=pd.Series(x2[0],index=['c','d','e','f','g'])
s2

c   -0.53.
d   -0.30.
e   -0.87.
f   -0.79.
g   -0.84.
dtype: float64

In [26]:
pd.concat([s1,s2])

a    7.46.
b    5.03.
c    5.07.
d    4.32.
e    3.95.
c   -0.53.
d   -0.30.
e   -0.87.
f   -0.79.
g   -0.84.
dtype: float64

In [28]:
pd.concat([s1,s2],axis=1)  #vea que se respetaron los indices repetidos

0      1
a 7.46.   nan.
b 5.03.   nan.
c 5.07. -0.53.
d 4.32. -0.30.
e 3.95. -0.87.
f  nan. -0.79.
g  nan. -0.84.

para no respetar el indice reset

In [30]:
s1.reset_index(drop=True)

0   7.46.
1   5.03.
2   5.07.
3   4.32.
4   3.95.
dtype: float64

In [32]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)],axis=1)

0      1
0 7.46. -0.53.
1 5.03. -0.30.
2 5.07. -0.87.
3 4.32. -0.79.
4 3.95. -0.84.

ahora concatenar dataframe


In [34]:
df1=pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a     b
0 0.76. 7.02.
1 6.25. 1.34.
2 8.59. 3.03.

In [38]:
 df2=pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'],index=[2,3,4])
df2

a      b
2 -0.70. -0.00.
3 -0.59. -0.73.
4 -0.14. -0.86.

In [39]:
pd.concat([df1,df2])

a      b
0  0.76.  7.02.
1  6.25.  1.34.
2  8.59.  3.03.
2 -0.70. -0.00.
3 -0.59. -0.73.
4 -0.14. -0.86.

In [40]:
pd.concat([df1,df2],axis=1)

a     b      a      b
0 0.76. 7.02.   nan.   nan.
1 6.25. 1.34.   nan.   nan.
2 8.59. 3.03. -0.70. -0.00.
3  nan.  nan. -0.59. -0.73.
4  nan.  nan. -0.14. -0.86.

In [41]:
pd.concat([df1,df2],axis=1,join='inner')

a     b      a      b
2 8.59. 3.03. -0.70. -0.00.

In [42]:
pd.concat([
           
           df1.reset_index(drop=True),
           
           df2.reset_index(drop=True)
           
           
           ],axis=1)

a     b      a      b
0 0.76. 7.02. -0.70. -0.00.
1 6.25. 1.34. -0.59. -0.73.
2 8.59. 3.03. -0.14. -0.86.

In [43]:
df1.append(df2)

a      b
0  0.76.  7.02.
1  6.25.  1.34.
2  8.59.  3.03.
2 -0.70. -0.00.
3 -0.59. -0.73.
4 -0.14. -0.86.

In [44]:
df1.append(df2).append(df2)

a      b
0  0.76.  7.02.
1  6.25.  1.34.
2  8.59.  3.03.
2 -0.70. -0.00.
3 -0.59. -0.73.
4 -0.14. -0.86.
2 -0.70. -0.00.
3 -0.59. -0.73.
4 -0.14. -0.86.

In [45]:
df1.T

0     1     2
a 0.76. 6.25. 8.59.
b 7.02. 1.34. 3.03.

In [46]:
df1.T.append(df2.T)

0     1      2      3      4
a 0.76. 6.25.  8.59.   nan.   nan.
b 7.02. 1.34.  3.03.   nan.   nan.
a  nan.  nan. -0.70. -0.59. -0.14.
b  nan.  nan. -0.00. -0.73. -0.86.