In [28]:
a=34   #shif enter para ejecutar
b=a+5

2+5

7

In [ ]:
b

39


In [ ]:
'Hola Mundo'

'Hola Mundo'

In [ ]:
x='Hola'
y='Mundo'

x+' '+ y

'Hola Mundo'

In [ ]:
[1,2,3,4] 

[1, 2, 3, 4]

In [ ]:
[1,2,3,4,5]+[10]

[1, 2, 3, 4, 5, 10]

In [ ]:
lista=[1,2,3,4,5]

In [ ]:
lista[0]

1

In [ ]:
lista[-1]

5

In [ ]:
import numpy as np # numpy para hacer operaciones

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [26]:
np.array([1,2,3,4,5])+10

array([11, 12, 13, 14, 15])

In [ ]:
np.array([1,2,3,4,5]).shape  # shape longitud vector

(5,)

In [ ]:
np.array([[1,2,3,4],[5,6,7,8]])  #una estructura matricial 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.array([[1,2,3,4],[5,6,7,8]]).shape 

(2, 4)

In [27]:
np.array([[1,2,3,4],[5,6,7,8]])[0]

array([1, 2, 3, 4])

In [29]:
np.array([[1,2,3,4],[5,6,7,8]])[0][2]

3